### REQUIRED

namespace: darthlukan

name: argocd_install

version: 1.2.1

readme: README.md

authors:
- Brian Tomlinson <btomlins@redhat.com>

description: Install ArgoCD on Kubernetes / OpenShift 4.x 

license:
- Apache-2.0

tags:
  - 'argocd'
  - 'k8s'
  - 'kubernetes'
  - 'openshift'
  - 'ocp'

dependencies: {}

repository: https://github.com/darthlukan/argocd_install

documentation: https://github.com/darthlukan/argocd_install/blob/master/README.md

homepage: https://github.com/darthlukan/argocd_install

issues: https://github.com/darthlukan/argocd_install/issues
