---
vars:
  operator_version_tag: "v0.0.13"
- name: Get latest ArgoCD CLI release
  github_release:
    user: argoproj-labs
    repo: argocd-operator
    action: latest_release
  register: operator_release

- name: Get ArgoCD Operator code from GitHub
  git:
    repo: https://github.com/argoproj-labs/argocd-operator.git
    dest: "{{ role_path }}/files/argocd-operator"
    version: "{{ operator_version_tag }}"

- name: Namespace {{ namespace }} is {{ state }}
  k8s:
    name: "{{ namespace }}" 
    kind: Namespace
    api_version: v1
    state: "{{ state }}"
    kubeconfig: "{{ kubeconfig }}"
...
